### ISSUE TITLE
new version of widget manager: error on changing group images

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/widget_manager#73]
i just came to edit an image for a pre-existing group and found that every time i see a fatal error. this occurs on both my live site and my dev site (elgg 1.12.6).
here's the dump:

```
oops.. a serious error has occurred.

Failed to load new ElggObject for GUID: 24224

IOException Object
(
[message:protected] => Failed to load new ElggObject for GUID: 24224
[string:Exception:private] => exception 'IOException' with message 'Failed to load new ElggObject for GUID: 24224' in /var/mysite/engine/classes/ElggObject.php:80
Stack trace:
#0 /var/mysite/engine/classes/Elgg/Database/EntityTable.php(100): ElggObject->__construct(Object(stdClass))
#1 /var/mysite/engine/lib/entities.php(372): Elgg\Database\EntityTable->rowToElggStar(Object(stdClass))
#2 /var/mysite/engine/classes/Elgg/Database/EntityTable.php(660): entity_row_to_elggstar(Object(stdClass))
#3 /var/mysite/engine/lib/entities.php(509): Elgg\Database\EntityTable->fetchFromSql('SELECT DISTINCT...', NULL)
#4 /var/mysite/engine/classes/Elgg/Database/EntityTable.php(471): _elgg_fetch_entities_from_sql('SELECT DISTINCT...', NULL)
#5 /var/mysite/engine/classes/Elgg/Database/EntityTable.php(174): Elgg\Database\EntityTable->getEntities(Array)
#6 /var/mysite/engine/classes/Elgg/Database/PrivateSettingsTable.php(304): Elgg\Database\EntityTable->get(24224)
#7 /var/mysite/engine/lib/private_settings.php(67): Elgg\Database\PrivateSettingsTable->get(24224, 'value')
#8 /var/mysite/engine/classes/ElggEntity.php(690): get_private_setting(24224, 'value')
#9 /var/mysite/engine/classes/ElggWidget.php(43): ElggEntity->getPrivateSetting('value')
#10 /var/mysite/mod/mentions/start.php(129): ElggWidget->__get('value')
#11 [internal function]: mentions_notification_handler('create', 'object', Object(ElggWidget))
#12 /var/mysite/engine/classes/Elgg/EventsService.php(56): call_user_func_array('mentions_notifi...', Array)
#13 /var/mysite/engine/classes/ElggEntity.php(1594): Elgg\EventsService->trigger('create', 'object', Object(ElggWidget))
#14 /var/mysite/engine/classes/Elgg/WidgetsService.php(94): ElggEntity->save()
#15 /var/mysite/engine/lib/widgets.php(39): Elgg\WidgetsService->createWidget(332, 'thewire_groups', 'groups', 2)
#16 /var/mysite/mod/widget_manager/lib/events.php(201): elgg_create_widget(332, 'thewire_groups', 'groups', 2)
#17 [internal function]: widget_manager_update_group_event_handler('update', 'group', Object(ElggGroup))
#18 /var/mysite/engine/classes/Elgg/EventsService.php(56): call_user_func_array('widget_manager_...', Array)
#19 /var/mysite/engine/classes/ElggEntity.php(1743): Elgg\EventsService->trigger('update', 'group', Object(ElggGroup))
#20 /var/mysite/engine/classes/ElggGroup.php(505): ElggEntity->update()
#21 /var/mysite/engine/classes/ElggEntity.php(1590): ElggGroup->update()
#22 /var/mysite/mod/group_tools/actions/groups/edit.php(135): ElggEntity->save()
#23 /var/mysite/engine/classes/Elgg/ActionsService.php(88): include('/var/www/html/d...')
#24 /var/mysite/engine/classes/Elgg/ActionsService.php(70): Elgg\ActionsService::includeFile('/var/www/html/d...')
#25 /var/mysite/engine/lib/actions.php(20): Elgg\ActionsService->execute('groups/edit')
#26 [internal function]: _elgg_action_handler(Array, 'action')
#27 /var/mysite/engine/classes/Elgg/Router.php(80): call_user_func('_elgg_action_ha...', Array, 'action')
#28 /var/mysite/index.php(60): Elgg\Router->route(Object(Elgg\Http\Request))
#29 {main}
[code:protected] => 0
[file:protected] => /var/mysite/engine/classes/ElggObject.php
[line:protected] => 80
[trace:Exception:private] => Array
(
[0] => Array
(
[file] => /var/mysite/engine/classes/Elgg/Database/EntityTable.php
[line] => 100
[function] => __construct
[class] => ElggObject
[type] => ->
[args] => Array
(
[0] => stdClass Object
(
[guid] => 24224
[type] => object
[subtype] => 3
[owner_guid] => 332
[site_guid] => 1
[container_guid] => 332
[access_id] => 2
[time_created] => 1454089943
[time_updated] => 1454089943
[last_action] => 1454089943
[enabled] => yes
[title] =>
[description] =>
)

)

)

[1] => Array
(
[file] => /var/mysite/engine/lib/entities.php
[line] => 372
[function] => rowToElggStar
[class] => Elgg\Database\EntityTable
[type] => ->
[args] => Array
(
[0] => stdClass Object
(
[guid] => 24224
[type] => object
[subtype] => 3
[owner_guid] => 332
[site_guid] => 1
[container_guid] => 332
[access_id] => 2
[time_created] => 1454089943
[time_updated] => 1454089943
[last_action] => 1454089943
[enabled] => yes
[title] =>
[description] =>
)

)

)

[2] => Array
(
[file] => /var/mysite/engine/classes/Elgg/Database/EntityTable.php
[line] => 660
[function] => entity_row_to_elggstar
[args] => Array
(
[0] => stdClass Object
(
[guid] => 24224
[type] => object
[subtype] => 3
[owner_guid] => 332
[site_guid] => 1
[container_guid] => 332
[access_id] => 2
[time_created] => 1454089943
[time_updated] => 1454089943
[last_action] => 1454089943
[enabled] => yes
[title] =>
[description] =>
)

)

)

[3] => Array
(
[file] => /var/mysite/engine/lib/entities.php
[line] => 509
[function] => fetchFromSql
[class] => Elgg\Database\EntityTable
[type] => ->
[args] => Array
(
[0] => SELECT DISTINCT e.* FROM entities e WHERE (e.guid IN (24224)) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY e.time_created desc LIMIT 0, 1
[1] =>
)

)

[4] => Array
(
[file] => /var/mysite/engine/classes/Elgg/Database/EntityTable.php
[line] => 471
[function] => _elgg_fetch_entities_from_sql
[args] => Array
(
[0] => SELECT DISTINCT e.* FROM entities e WHERE (e.guid IN (24224)) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY e.time_created desc LIMIT 0, 1
[1] =>
)

)

[5] => Array
(
[file] => /var/mysite/engine/classes/Elgg/Database/EntityTable.php
[line] => 174
[function] => getEntities
[class] => Elgg\Database\EntityTable
[type] => ->
[args] => Array
(
[0] => Array
(
[guid] => 24224
[limit] => 1
[site_guids] =>
)

)

)

[6] => Array
(
[file] => /var/mysite/engine/classes/Elgg/Database/PrivateSettingsTable.php
[line] => 304
[function] => get
[class] => Elgg\Database\EntityTable
[type] => ->
[args] => Array
(
[0] => 24224
)

)

[7] => Array
(
[file] => /var/mysite/engine/lib/private_settings.php
[line] => 67
[function] => get
[class] => Elgg\Database\PrivateSettingsTable
[type] => ->
[args] => Array
(
[0] => 24224
[1] => value
)

)

[8] => Array
(
[file] => /var/mysite/engine/classes/ElggEntity.php
[line] => 690
[function] => get_private_setting
[args] => Array
(
[0] => 24224
[1] => value
)

)

[9] => Array
(
[file] => /var/mysite/engine/classes/ElggWidget.php
[line] => 43
[function] => getPrivateSetting
[class] => ElggEntity
[type] => ->
[args] => Array
(
[0] => value
)

)

[10] => Array
(
[file] => /var/mysite/mod/mentions/start.php
[line] => 129
[function] => __get
[class] => ElggWidget
[type] => ->
[args] => Array
(
[0] => value
)

)

[11] => Array
(
[function] => mentions_notification_handler
[args] => Array
(
[0] => create
[1] => object
[2] => ElggWidget Object
(
[url_override:protected] =>
[icon_override:protected] =>
[temp_metadata:protected] => Array
(
)

[temp_annotations:protected] => Array
(
)

[temp_private_settings:protected] => Array
(
)

[volatile:protected] => Array
(
)

[tables_split:protected] => 2
[tables_loaded:protected] => 0
[attributes:protected] => Array
(
[time_created] => 1454089943
[guid] => 24224
[type] => object
[subtype] => 3
[owner_guid] => 332
[container_guid] => 332
[site_guid] => 1
[access_id] => 2
[time_updated] => 1454089943
[last_action] => 1454089943
[enabled] => yes
[title] =>
[description] =>
)

[valid:protected] =>
)

)

)

[12] => Array
(
[file] => /var/mysite/engine/classes/Elgg/EventsService.php
[line] => 56
[function] => call_user_func_array
[args] => Array
(
[0] => mentions_notification_handler
[1] => Array
(
[0] => create
[1] => object
[2] => ElggWidget Object
(
[url_override:protected] =>
[icon_override:protected] =>
[temp_metadata:protected] => Array
(
)

[temp_annotations:protected] => Array
(
)

[temp_private_settings:protected] => Array
(
)

[volatile:protected] => Array
(
)

[tables_split:protected] => 2
[tables_loaded:protected] => 0
[attributes:protected] => Array
(
[time_created] => 1454089943
[guid] => 24224
[type] => object
[subtype] => 3
[owner_guid] => 332
[container_guid] => 332
[site_guid] => 1
[access_id] => 2
[time_updated] => 1454089943
[last_action] => 1454089943
[enabled] => yes
[title] =>
[description] =>
)

[valid:protected] =>
)

)

)

)

[13] => Array
(
[file] => /var/mysite/engine/classes/ElggEntity.php
[line] => 1594
[function] => trigger
[class] => Elgg\EventsService
[type] => ->
[args] => Array
(
[0] => create
[1] => object
[2] => ElggWidget Object
(
[url_override:protected] =>
[icon_override:protected] =>
[temp_metadata:protected] => Array
(
)

[temp_annotations:protected] => Array
(
)

[temp_private_settings:protected] => Array
(
)

[volatile:protected] => Array
(
)

[tables_split:protected] => 2
[tables_loaded:protected] => 0
[attributes:protected] => Array
(
[time_created] => 1454089943
[guid] => 24224
[type] => object
[subtype] => 3
[owner_guid] => 332
[container_guid] => 332
[site_guid] => 1
[access_id] => 2
[time_updated] => 1454089943
[last_action] => 1454089943
[enabled] => yes
[title] =>
[description] =>
)

[valid:protected] =>
)

)

)

[14] => Array
(
[file] => /var/mysite/engine/classes/Elgg/WidgetsService.php
[line] => 94
[function] => save
[class] => ElggEntity
[type] => ->
[args] => Array
(
)

)

[15] => Array
(
[file] => /var/mysite/engine/lib/widgets.php
[line] => 39
[function] => createWidget
[class] => Elgg\WidgetsService
[type] => ->
[args] => Array
(
[0] => 332
[1] => thewire_groups
[2] => groups
[3] => 2
)

)

[16] => Array
(
[file] => /var/mysite/mod/widget_manager/lib/events.php
[line] => 201
[function] => elgg_create_widget
[args] => Array
(
[0] => 332
[1] => thewire_groups
[2] => groups
[3] => 2
)

)

[17] => Array
(
[function] => widget_manager_update_group_event_handler
[args] => Array
(
[0] => update
[1] => group
[2] => ElggGroup Object
(
[url_override:protected] =>
[icon_override:protected] =>
[temp_metadata:protected] => Array
(
)

[temp_annotations:protected] => Array
(
)

[temp_private_settings:protected] => Array
(
)

[volatile:protected] => Array
(
)

[tables_split:protected] => 2
[tables_loaded:protected] => 2
[attributes:protected] => Array
(
[guid] => 332
[type] => group
[subtype] => 0
[owner_guid] => 2
[site_guid] => 1
[container_guid] => 2
[access_id] => 2
[time_created] => 1294192276
[time_updated] => 1417917764
[last_action] => 1294192276
[enabled] => yes
[name] => cosmic interactions
[description] => <p>sharing about 'ufos', 'extra terrestrials', 'inter dimensional visitors' and any related 'non earth' experiences of our cosmos.</p>
)

[valid:protected] =>
)

)

)

[18] => Array
(
[file] => /var/mysite/engine/classes/Elgg/EventsService.php
[line] => 56
[function] => call_user_func_array
[args] => Array
(
[0] => widget_manager_update_group_event_handler
[1] => Array
(
[0] => update
[1] => group
[2] => ElggGroup Object
(
[url_override:protected] =>
[icon_override:protected] =>
[temp_metadata:protected] => Array
(
)

[temp_annotations:protected] => Array
(
)

[temp_private_settings:protected] => Array
(
)

[volatile:protected] => Array
(
)

[tables_split:protected] => 2
[tables_loaded:protected] => 2
[attributes:protected] => Array
(
[guid] => 332
[type] => group
[subtype] => 0
[owner_guid] => 2
[site_guid] => 1
[container_guid] => 2
[access_id] => 2
[time_created] => 1294192276
[time_updated] => 1417917764
[last_action] => 1294192276
[enabled] => yes
[name] => cosmic interactions
[description] => <p>sharing about 'ufos', 'extra terrestrials', 'inter dimensional visitors' and any related 'non earth' experiences of our cosmos.</p>
)

[valid:protected] =>
)

)

)

)

[19] => Array
(
[file] => /var/mysite/engine/classes/ElggEntity.php
[line] => 1743
[function] => trigger
[class] => Elgg\EventsService
[type] => ->
[args] => Array
(
[0] => update
[1] => group
[2] => ElggGroup Object
(
[url_override:protected] =>
[icon_override:protected] =>
[temp_metadata:protected] => Array
(
)

[temp_annotations:protected] => Array
(
)

[temp_private_settings:protected] => Array
(
)

[volatile:protected] => Array
(
)

[tables_split:protected] => 2
[tables_loaded:protected] => 2
[attributes:protected] => Array
(
[guid] => 332
[type] => group
[subtype] => 0
[owner_guid] => 2
[site_guid] => 1
[container_guid] => 2
[access_id] => 2
[time_created] => 1294192276
[time_updated] => 1417917764
[last_action] => 1294192276
[enabled] => yes
[name] => cosmic interactions
[description] => <p>sharing about 'ufos', 'extra terrestrials', 'inter dimensional visitors' and any related 'non earth' experiences of our cosmos.</p>
)

[valid:protected] =>
)

)

)

[20] => Array
(
[file] => /var/mysite/engine/classes/ElggGroup.php
[line] => 505
[function] => update
[class] => ElggEntity
[type] => ->
[args] => Array
(
)

)

[21] => Array
(
[file] => /var/mysite/engine/classes/ElggEntity.php
[line] => 1590
[function] => update
[class] => ElggGroup
[type] => ->
[args] => Array
(
)

)

[22] => Array
(
[file] => /var/mysite/mod/group_tools/actions/groups/edit.php
[line] => 135
[function] => save
[class] => ElggEntity
[type] => ->
[args] => Array
(
)

)

[23] => Array
(
[file] => /var/mysite/engine/classes/Elgg/ActionsService.php
[line] => 88
[args] => Array
(
[0] => /var/mysite/mod/group_tools/actions/groups/edit.php
)

[function] => include
)

[24] => Array
(
[file] => /var/mysite/engine/classes/Elgg/ActionsService.php
[line] => 70
[function] => includeFile
[class] => Elgg\ActionsService
[type] => ::
[args] => Array
(
[0] => /var/mysite/mod/group_tools/actions/groups/edit.php
)

)

[25] => Array
(
[file] => /var/mysite/engine/lib/actions.php
[line] => 20
[function] => execute
[class] => Elgg\ActionsService
[type] => ->
[args] => Array
(
[0] => groups/edit
)

)

[26] => Array
(
[function] => _elgg_action_handler
[args] => Array
(
[0] => Array
(
[0] => groups
[1] => edit
)

[1] => action
)

)

[27] => Array
(
[file] => /var/mysite/engine/classes/Elgg/Router.php
[line] => 80
[function] => call_user_func
[args] => Array
(
[0] => _elgg_action_handler
[1] => Array
(
[0] => groups
[1] => edit
)

[2] => action
)

)

[28] => Array
(
[file] => /var/mysite/index.php
[line] => 60
[function] => route
[class] => Elgg\Router
[type] => ->
[args] => Array
(
[0] => Elgg\Http\Request Object
(
[attributes] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
)

)

[request] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
[__elgg_token] => eMbJJxw1PfybU7yqa44DLg
[__elgg_ts] => 1454089934
[name] => cosmic interactions
[description] => <p>sharing about 'ufos', 'extra terrestrials', 'inter dimensional visitors' and any related 'non earth' experiences of our cosmos.</p>
[order] => 14
[membership] => 2
[vis] => 2
[content_access_mode] => unrestricted
[group_default_access] => 2
[owner_guid] => 2
[widget_manager_enable] => yes
[file_enable] => yes
[forum_enable] => yes
[photos_enable] => yes
[tp_images_enable] => yes
[sets_enable] => yes
[liked_content_enable] => yes
[pages_enable] => yes
[blog_enable] => yes
[videolist_enable] => yes
[bookmarks_enable] => yes
[thewire_enable] => yes
[activity_enable] => yes
[related_groups_enable] => no
[group_guid] => 332
)

)

[query] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
[__elgg_uri] => /action/groups/edit
)

)

[server] => Symfony\Component\HttpFoundation\ServerBag Object
(
[parameters:protected] => Array
(
[USER] => nginx
[HOME] => /var/lib/nginx
[FCGI_ROLE] => RESPONDER
[SCRIPT_FILENAME] => /var/mysite/index.php
[QUERY_STRING] => __elgg_uri=/action/groups/edit&
[REQUEST_METHOD] => POST
[CONTENT_TYPE] => multipart/form-data; boundary=---------------------------18539516628270741931445972283
[CONTENT_LENGTH] => 154414
[SCRIPT_NAME] => /index.php
[REQUEST_URI] => /action/groups/edit
[DOCUMENT_URI] => /index.php
[DOCUMENT_ROOT] => /var/mysite
[SERVER_PROTOCOL] => HTTP/1.1
[GATEWAY_INTERFACE] => CGI/1.1
[SERVER_SOFTWARE] => nginx/1.8.0
[REMOTE_ADDR] => 127.0.0.1
[REMOTE_PORT] => 36100
[SERVER_ADDR] => 127.0.0.1
[SERVER_PORT] => 80
[SERVER_NAME] => mysite
[REDIRECT_STATUS] => 200
[HTTP_HOST] => mysite
[HTTP_USER_AGENT] => Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
[HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
[HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.5
[HTTP_ACCEPT_ENCODING] => gzip, deflate
[HTTP_DNT] => 1
[HTTP_REFERER] => http://mysite/zones/edit/332
[HTTP_COOKIE] => _pk_id.1.e51c=b92ace032c9434d6.1453817098.12.1454089935.1454089677.; cookieconsent_dismissed=yes; elggperm=z9jmaFlDuHCSTfG2k7xQJu1WGZiBIQtH; sorted-videolist=%7B%22context%22%3A%22videolist%22%2C%22list_type%22%3A%22list%22%2C%22limit%22%3A%2212%22%2C%22contain%22%3A%22all%22%2C%22sort%22%3A%22created_d%22%2C%22timing%22%3A%22all%22%2C%22status%22%3A%22all%22%7D; Elgg=5hpjfhcnv1op9hhvqqkui12c57; sorted-members=%7B%22context%22%3A%22members%22%2C%22list_type%22%3A%22list%22%2C%22limit%22%3A%2212%22%2C%22contain%22%3A%2212%22%2C%22sort%22%3A%22created_d%22%2C%22timing%22%3A%22all%22%2C%22status%22%3A%22all%22%7D; sorted-blog=%7B%22context%22%3A%22blog%22%2C%22list_type%22%3A%22list%22%2C%22limit%22%3A%2212%22%2C%22contain%22%3A%22all%22%2C%22sort%22%3A%22created_d%22%2C%22timing%22%3A%22all%22%2C%22status%22%3A%22all%22%7D; _pk_ses.1.e51c=*
[HTTP_CONNECTION] => keep-alive
[HTTP_CONTENT_TYPE] => multipart/form-data; boundary=---------------------------18539516628270741931445972283
[HTTP_CONTENT_LENGTH] => 154414
[PHP_SELF] => /index.php
[REQUEST_TIME_FLOAT] => 1454089943.1694
[REQUEST_TIME] => 1454089943
)

)

[files] => Symfony\Component\HttpFoundation\FileBag Object
(
[parameters:protected] => Array
(
[icon] => Symfony\Component\HttpFoundation\File\UploadedFile Object
(
[test:Symfony\Component\HttpFoundation\File\UploadedFile:private] =>
[originalName:Symfony\Component\HttpFoundation\File\UploadedFile:private] => jedi squirrels.jpg
[mimeType:Symfony\Component\HttpFoundation\File\UploadedFile:private] => image/jpeg
[size:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 149413
[error:Symfony\Component\HttpFoundation\File\UploadedFile:private] => 0
[pathName:SplFileInfo:private] => /tmp/phpKIiAyl
[fileName:SplFileInfo:private] => phpKIiAyl
)

)

)

[cookies] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
[_pk_id_1_e51c] => b92ace032c9434d6.1453817098.12.1454089935.1454089677.
[cookieconsent_dismissed] => yes
[elggperm] => z9jmaFlDuHCSTfG2k7xQJu1WGZiBIQtH
[sorted-videolist] => {"context":"videolist","list_type":"list","limit":"12","contain":"all","sort":"created_d","timing":"all","status":"all"}
[Elgg] => 5hpjfhcnv1op9hhvqqkui12c57
[sorted-members] => {"context":"members","list_type":"list","limit":"12","contain":"12","sort":"created_d","timing":"all","status":"all"}
[sorted-blog] => {"context":"blog","list_type":"list","limit":"12","contain":"all","sort":"created_d","timing":"all","status":"all"}
[_pk_ses_1_e51c] => *
)

)

[headers] => Symfony\Component\HttpFoundation\HeaderBag Object
(
[headers:protected] => Array
(
[content-type] => Array
(
[0] => multipart/form-data; boundary=---------------------------18539516628270741931445972283
)

[content-length] => Array
(
[0] => 154414
)

[host] => Array
(
[0] => mysite
)

[user-agent] => Array
(
[0] => Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
)

[accept] => Array
(
[0] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
)

[accept-language] => Array
(
[0] => en-US,en;q=0.5
)

[accept-encoding] => Array
(
[0] => gzip, deflate
)

[dnt] => Array
(
[0] => 1
)

[referer] => Array
(
[0] => http://mysite/zones/edit/332
)

[cookie] => Array
(

)

[connection] => Array
(
[0] => keep-alive
)

)

[cacheControl:protected] => Array
(
)

)

[content:protected] =>
[languages:protected] =>
[charsets:protected] =>
[encodings:protected] =>
[acceptableContentTypes:protected] =>
[pathInfo:protected] =>
[requestUri:protected] => /action/groups/edit
[baseUrl:protected] =>
[basePath:protected] =>
[method:protected] =>
[format:protected] =>
[session:protected] =>
[locale:protected] =>
[defaultLocale:protected] => en
)

)

)

)

[previous:Exception:private] =>
)
```

**Comment by jdalsem** [comment]
Based on the stack trace and the fact that i can not reproduce it, i am assuming that the problem is in the mentions plugin (see line 11 in the stacktrace) and not in this plugin.

**Comment by propertunist** [comment]
good eye! i did not see that reference to mentions. i disabled it and can correctly save the image.

**Comment by propertunist** [comment]
i just tested by disabling widget manager and mentions and seeing if there is a pattern i can identify. i found that the error could be triggered, but not for all of my test site's groups and only when widget manager was enabled. so it's a fairly obscure bug it seems. i will look again at this when i have more timespace available.
